server:
  port: 9309

app:
  id: springboot-apollo
apollo:
  meta: http://10.215.10.243:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true



logging:
  level:
    overun:
      controller: debug
